name: Make Build (Windows MinGW)

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2 + MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-binutils

    - name: Build with Makefile
      shell: msys2 {0}
      run: make

    - name: Upload Release folder
      uses: actions/upload-artifact@v4
      with:
        name: build-Release
        path: build/Release/*

    - name: Upload Debug folder
      uses: actions/upload-artifact@v4
      with:
        name: build-Debug
        path: build/Debug/*